name: Deploy

on: workflow_dispatch

jobs:

  Pypi:
   runs-on: ubuntu-latest

   env:
     TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
     PYPI_TARGET_REPO: ${{ secrets.PYPI_TARGET_REPO }}
     
   steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Package
      run: |
        tox -e build

    - name: Deploy
      run: |
        tox -e deploy
