name: Deploy

on: 
  workflow_dispatch:
    inputs:
      target_environment:
        description: Target GitHub Environment
        default: DEVELOP
        required: true

jobs:

  Pypi:
   runs-on: ubuntu-latest
   
   environment: ${{github.event.inputs.target_environment}}

   env:
     TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
     PYPI_TARGET_REPO: ${{ secrets.PYPI_TARGET_REPO }}
 
   steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Package
      run: |
        tox -e build

    - name: Deploy
      env:
         TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
         PYPI_TARGET_REPO: ${{ secrets.PYPI_TARGET_REPO }}
      
      run: |
        tox -e deploy
