name: QA

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Code Quality
      run: |
        tox -e codequality
        
    - name: Run Unittests and Code Coverage
      run: |
        tox -e coverage
